[package]
name = "asmo"
version = "0.3.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
local-ip-address = "0.6"
scopeguard = "1"